# Generated by Django 4.1.4 on 2023-02-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expence', '0002_rename_expense_credit_debit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='amount',
            new_name='cramounts',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='date',
            new_name='crdates',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='description',
            new_name='crdescriptions',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='amount',
            new_name='deamounts',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='date',
            new_name='dedates',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='description',
            new_name='dedescriptions',
        ),
    ]
