# Generated by Django 4.1.4 on 2023-02-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expence', '0003_rename_amount_credit_cramounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='user',
        ),
    ]
